### ISSUE TITLE
Stream has already been listened to

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#66]
During migration to Alfred I faced with next error:
```
Unhandled exception:
Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:635:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#3      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114:10)
#4      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86:16)
#5      _ForwardingStream.listen (dart:async/stream_pipe.dart:81:12)
#6      _HttpIncoming.listen (dart:_http/http_impl.dart:444:8)
#7      _HttpRequest.listen (dart:_http/http_impl.dart:524:22)
#8      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:49:16)
#9      _BoundSinkStream.listen (dart:async/stream_transformers.dart:171:9)
#10     Stream.fold (dart:async/stream.dart:798:14)
#11     _process.asText (package:alfred/src/body_parser/http_body.dart:238:58)
#12     _process.asText (package:alfred/src/body_parser/http_body.dart:233:26)
#13     _process (package:alfred/src/body_parser/http_body.dart:281:28)
#14     HttpBodyHandler.processRequest (package:alfred/src/body_parser/http_body.dart:119:24)
#15     RequestHelpers.body (package:alfred/src/extensions/request_helpers.dart:16:30)
#16     main.<anonymous closure> (file:///D:/code/zakupki/parser_monitor_server/bin/parser_monitor_server.dart:173:21)
<asynchronous suspension>
#17     Alfred._incomingRequest (package:alfred/src/alfred.dart:291:15)
<asynchronous suspension>
#18     _QueuedFuture.execute (package:queue/src/dart_queue_base.dart:26:16)
<asynchronous suspension>
```

What can cause it?

My app have several handlers and flutter app send at start few requests to them.

**Comment by bubnenkoff** [comment]
If anybody will faced with this problem the reason is simple. 
```
final body = await req.body as Map<String, dynamic>;
```
is getting body if request, But below this I tried to access to object again:
```
print(req.body);
```
instead of:
```
print(body);
```

**Comment by rknell** [comment]
Thanks for coming back and posting your workaround
