### ISSUE TITLE
Converting object to an encodable object failed

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#69]
```
  // [[ ], [ ], [ ]] <-- answer from DB is this format should be: [{}, {}, {}]
  static List<Map<dynamic, dynamic>> listFromArrays(lists) {
    var result = <Map<dynamic, dynamic>>[];
    int index = 0;
    for (List list in lists) {
      result.add({index: list[0]});  // do not work
      // result.add({'foo': list[0]});
    }
    return result;
  }
```  

I am trying to create list of objects like:
`[{1:"notifications"}]`

with `String` as key all works fine. But with int I am getting an error:
```
2021-09-15 16:06:59.523712 - error - Converting object to an encodable object failed: _LinkedHashMap len:1
2021-09-15 16:06:59.523712 - error - #0      _JsonStringifier.writeObject (dart:convert/json.dart:688:7)
#1      _JsonStringifier.writeList (dart:convert/json.dart:736:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:718:7)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:679:9)
#4      _JsonStringifier.writeMap (dart:convert/json.dart:769:7)
#5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:724:21)
#6      _JsonStringifier.writeObject (dart:convert/json.dart:679:9)
#7      _JsonStringStringifier.printOn (dart:convert/json.dart:877:17)
#8      _JsonStringStringifier.stringify (dart:convert/json.dart:862:5)
#9      JsonEncoder.convert (dart:convert/json.dart:262:30)
#10     JsonCodec.encode (dart:convert/json.dart:172:45)
#11     jsonEncode (dart:convert/json.dart:81:10)
#12     _jsonHandler (package:alfred/src/type_handlers/json_type_handlers.dart:9:13)
#13     Alfred._handleResponse (package:alfred/src/alfred.dart:368:36)
#14     Alfred._incomingRequest (package:alfred/src/alfred.dart:290:17)
<asynchronous suspension>
#15     _QueuedFuture.execute (package:queue/src/dart_queue_base.dart:26:16)
<asynchronous suspension>
```

upd there is issue https://github.com/google/json_serializable.dart/issues/434
But what I should to do if client lib require integer as keyes? https://github.com/lcuis/search_choices/blob/master/example/lib/main.dart#L13

**Comment by bubnenkoff** [comment]
I am closing issue. It's not related with Alfred. JSON keys can't be `int` but `Map`'s can.
